### PR TITLE
Improve handling of scalars in NetCDFTimeConverter.convert

### PR DESCRIPTION
**Pull request by spencerkclark**
This provides a simple fix for #45.

### CODE REVIEW

**Comment by bjlittle** [comment]
@spencerkclark Once https://github.com/SciTools/nc-time-axis/pull/66 lands (hopefully), you'll need to rebase, then I'll review and merge :+1:

**Comment by bjlittle** [comment]
@spencerkclark Time to rebase :+1: 

Then let's get this finally banked :smiley:

**Comment by spencerkclark** [comment]
Awesome, should be all set @bjlittle -- I also removed an errant `print` statement that seemed to have crept in during #66.

**Comment by bjlittle** [comment]
I'll get to this, this evening :+1: 

Awesome!

**Review by bjlittle — APPROVED** [review]

**Comment by bjlittle** [comment]
@spencerkclark Perfect, thanks :beers:

**Pull request merged**
