### PR TITLE
Add travis

### PR DESCRIPTION
**Pull request by lbdreyer**
This depends on PR #3 and #4

### CODE REVIEW

**Comment by lbdreyer** [comment]
I don't quite understand why the travis build is failing.
When I ran 
```python setup.py test```
 on my desktop it ran fine, but when I followed the travis.yml instructions it got the same error.
I suppose there maybe something different with my desktop env and the conda env. I'm looking into this now

**Comment by lbdreyer** [comment]
On my desktop:
```
>>> import netcdftime
>>> netcdftime
<module 'netcdftime' from '/path/to/site-packages/netcdftime.pyc'>
```

In the Conda env:
```
>>> import netcdftime
>>> netcdftime
<module 'netcdftime' from '/path/to/site-packages/netcdftime/__init__.pyc'>
```

Not sure what's going on on my desktop

**Comment by lbdreyer** [comment]
There are some differences between the netcdf4 version available on the desktops and through the conda env:

* __Number differences__

DESKTOP
```
>>> utime = netcdftime.utime('days since 2004-01-01 00:00', '365_day')
>>> print utime.num2date(0.0004)
2004-01-01 00:00:35
```

CONDA
```
>>> utime = netcdftime.utime('days since 2004-01-01 00:00', '365_day')
>>> print utime.num2date(0.0004)
2004-01-01 00:00:34
```

* __datetime object__



DESKTOP
```
>>> val = netcdftime.datetime(2014, 8, 12)
>>> val.calendar = '360_day'
>>> 
```

CONDA
```
>>> val = netcdftime.datetime(2014, 8, 12)
>>> val.calendar = '360_day'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'netcdftime._datetime.datetime' object has no attribute 'calendar'
```

:cry:

**Comment by bjlittle** [comment]
@lbdreyer Pin at 1.0.2 and raise an issue to update? for now ...

**Comment by bjlittle** [comment]
@lbdreyer Nice :+1: 

How about creating that issue before we forget?

**Comment by bjlittle** [comment]
See Issue https://github.com/SciTools/nc-time-axis/issues/8.

**Comment by lbdreyer** [comment]
I have:
* Opened issue #8 
* Removed Python 3 build as there isn't a netcdf4 1.0.2 python 3 build
* Allowed non-integer tick locations

**Comment by bjlittle** [comment]
@lbdreyer Awesome!

**Pull request merged**
