### PR TITLE
Update CITATION.cff with contributor ORCIDs

### PR DESCRIPTION
**Pull request by bjlittle**
### Description

This PR updates the `CITATION.cff` file with most of our contributor [ORCID](https://orcid.org/) details, as per issue #135.

I'm rolling with the 80/20 rule i.e., we can bank the majority of the ORCIDs now.

Note that, I've ordered the entries alphabetically by surname, which seems reasonable.

I'll leave issue #135 open and pinned for now. Perhaps our remaining contributors may get back to us at some point, or raise a pull-request themselves. We'll see ...

### CODE REVIEW

**Review by spencerkclark — COMMENTED** [review]
Thanks @bjlittle!  I will maybe defer to @pelson and @lbdreyer on the order of the names, since as I understand it they were the ones to initially conceptualize and package up nc-time-axis.  This otherwise looks good to me.

**Comment by pelson** [comment]
> I will maybe defer to @pelson and @lbdreyer on the order of the names, since as I understand it they were the ones to initially conceptualize and package up nc-time-axis

Sure, but it is a team effort to keep it going, so from my perspective, I'm happy with whatever order is chosen, including if Laura wants to be lead-author.

**Comment by bjlittle** [comment]
Okay, I totally hear what @pelson saying, but I love the intent of @spencerkclark's point, so let's recognise that and seed the list with @lbdreyer and @pelson who were the creators of `nc-time-axis` 💯

**Review by spencerkclark — APPROVED** [review]
@bjlittle indeed I like that idea a lot!  Thanks @pelson for weighing in.  Assuming @lbdreyer is good with it too, I think this is ready to go.

**Comment by lbdreyer** [comment]
I'm not concerned by the order of names, so happy to go with alphabetical or as it currently is

**Comment by spencerkclark** [comment]
Yes, thanks @bjlittle and @lbdreyer!  I’ll go ahead and merge.

**Pull request merged**
