### PR TITLE
mods needed for cftime PR #202

### PR DESCRIPTION
**Pull request by jswhit2**
see discussion at https://github.com/Unidata/cftime/issues/198

Small backwards compatibile change to one of the tests needed so that they pass with https://github.com/Unidata/cftime/pull/202

### CODE REVIEW

**Comment by jswhit** [comment]
commented out a test in test_NetCDFTimeDateLocator.py that removes year zero.  Year zero in a reference date is now explicity checked for in cftime.datetime (an error is raised if it is used).

**Review by trexfeathers — CHANGES_REQUESTED** [review]
Hi @jswhit thanks for you vigilance, and sorry that the support for nc-time-axis is so sporadic. I will keep trying my best to carve out time when I can.

Having read around the issues discussed here, I've suggested some alternatives for dealing with them. Hopefully they sound sensible to you.

Also: please can you sign the SciTools CLA (see the [Governance](https://scitools.org.uk/organisation.html#governance) notes for more detail), otherwise this PR cannot be merged even after it has been reviewed.

**Comment by jswhit** [comment]
CLA signed and comments addressed.

**Comment by trexfeathers** [comment]
@jswhit are you happy with my [suggested change to `nc_time_axis.NetCDFTimeDateLocator.tick_values()`](https://github.com/SciTools/nc-time-axis/pull/51#discussion_r558473193)? That should get the tests passing

**Comment by spencerkclark** [comment]
@jswhit @trexfeathers, I made a PR to @jswhit's branch making @trexfeathers's suggested fix.  Let me know if that looks good; it would be great to get this PR merged so that a new release of nc-time-axis can be issued (#54).

**Comment by bjlittle** [comment]
Closed by #66

**Pull request closed without merging**
