### PR TITLE
gha test

### PR DESCRIPTION
**Pull request by bjlittle**

### CODE REVIEW

**Comment by bjlittle** [comment]
Okay, so this simple gha is **not** being triggered, which is somewhat baffling... :confused:

**Comment by rcomer** [comment]
Is there a switch to flick in the repo settings?  Possibly clutching at straws but I notice there are no current GHA is nc-time-axis.

**Comment by bjlittle** [comment]
> Is there a switch to flick in the repo settings?  Possibly clutching at straws but I notice there are no current GHA in nc-time-axis.

@rcomer Nope, no obvious switches. I've looked everywhere, cross-compared with other than operational repo, scoured the docs and come up blank.

My thinking is that perhaps we need to bank the first action to bootstrap the workflows... But that's complete speculation.

Dunno. But I'd be happy for anyone to advise if they've seen this behaviour before. Perhaps I've done something obviously wrong, but the GHAs are pretty much similar to others the definitely are operational.

Otherwise, my suggestion is to merge this PR to see what happens. We can always reset the `HEAD` on `main` afterwards.

Dunno?! I'm speaking to the wisdom of the crowd here...

**Review by rcomer — APPROVED** [review]
OK let’s just see what happens…

**Comment by bjlittle** [comment]
@rcomer Well... ain't that a thing. Good to know, right?

Thanks for taking the plunge 🎉

**Pull request merged**
