### PR TITLE
Made use of the install_requires information in setup.py to remove the requirements.txt

### LINKED ISSUE #27: Use of 'matplotlib<2' not what you think
We have matplotlib<2 in our requirements.txt, which is being used by conda.
Turns out, that doesn't do exactly what you'd expect...

```
conda create -n nc_time_axis pip 'matplotlib<2' netcdf4
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment /Users/pelson/miniconda/envs/nc_time_axis:

The following NEW packages will be INSTALLED:

    ca-certificates: 2017.7.27.1-0        conda-forge
    certifi:         2017.7.27.1-py36_0   conda-forge
    curl:            7.54.1-0             conda-forge
    cycler:          0.10.0-py36_0        conda-forge
    freetype:        2.6.3-1              conda-forge
    hdf4:            4.2.12-0             conda-forge
    hdf5:            1.8.18-0             conda-forge
    jpeg:            9b-0                 conda-forge
    krb5:            1.14.2-0             conda-forge
    libgfortran:     3.0.0-0              conda-forge
    libnetcdf:       4.4.1.1-5            conda-forge
    libpng:          1.6.28-0             conda-forge
    libssh2:         1.8.0-1              conda-forge
    matplotlib:      2.0.0rc2-np112py36_2 conda-forge
    mkl:             2017.0.3-0           defaults   
    ncurses:         5.9-10               conda-forge
    netcdf4:         1.2.9-py36_1         conda-forge
    numpy:           1.12.1-py36_0        defaults   
```

Notice how a version before 2.0.0 *has* been selected, it's just that it is a 2.0 release candidate. I attribute this to be a bug in conda, but for now, we need to be more explicit and replace 'matplotlib<2' with 'matplotlib 1*'.

### PR DESCRIPTION
**Pull request by pelson**
Travis CI is now using that information.

Closes #27.

cc: @bjlittle

### CODE REVIEW

**Comment by pelson** [comment]
cc: @LukeC92 for your recent improvement in #26 that allowed this.

**Comment by pelson** [comment]
As background: https://packaging.python.org/discussions/install-requires-vs-requirements/

**Comment by lbdreyer** [comment]
The reduction in code coverage is because coveralls is now including the lines of code from mock, pbr, funcsigs, and pep8 and they have a lot of code that we won't be hitting during the tests.

**Comment by pelson** [comment]
So happy to merge?

**Comment by pelson** [comment]
Ping @lbdreyer. (only in the interests of moving things along, no particular urgency)

**Comment by lbdreyer** [comment]
> So happy to merge?

Not enormously considering the code coverage result. This change shouldn't affect code coverage but we can't tell that and the code coverage seems worse than it is.

**Comment by pelson** [comment]
> Not enormously considering the code coverage result. This change shouldn't affect code coverage but we can't tell that and the code coverage seems worse than it is.

Could you give me a tangible action to move this forwards? I've not actually added *any* code in this change... short of testing the ``setup.py`` there is very little means of actually adding any coverage.

**Comment by lbdreyer** [comment]
Ideally, I would like to stop it testing code coverage from mock, pbr, funcsigs, and pep8

**Comment by pelson** [comment]
I tweaked the coveragerc to only cover nc_time_axis. Seems to have done the trick...

**Pull request merged**
